var Mathematics = 75.25;
var Biology = 65;
var Chemistry = 80;
var Physics = 35.45;
var Bangla = 99.50;
var totalSubject = Mathematics + Biology + Chemistry + Physics + Bangla;
console.log(totalSubject);
var totalPerson = 5;
var averageNumber = totalSubject / totalPerson;
averageNumber = averageNumber.toFixed(2);
console.log(averageNumber);